name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug", "triage"]
projects: ["ustad-android-poc"]
assignees:
  - erdalgunes
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0 (Default)
        - 0.9.0
        - 0.8.0
        - Other (please specify in additional context)
    validations:
      required: true
  
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you testing on?
      options:
        - Pixel 6
        - Pixel 5
        - Samsung Galaxy S21
        - Samsung Galaxy Note 20
        - OnePlus 9
        - Emulator
        - Other (please specify in additional context)
    validations:
      required: true
  
  - type: dropdown
    id: android-version
    attributes:
      label: Android Version
      description: What Android version is the device running?
      options:
        - Android 14 (API 34)
        - Android 13 (API 33)
        - Android 12 (API 31-32)
        - Android 11 (API 30)
        - Android 10 (API 29)
        - Other (please specify in additional context)
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true