blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/erdalgunes/ustad-android-poc/discussions
    about: Ask questions and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/erdalgunes/ustad-android-poc/wiki
    about: Check the project wiki for detailed documentation