name: General Inquiry
description: Ask a question or make a general inquiry
title: "[QUESTION] "
labels: ["question", "help-wanted"]
projects: ["ustad-android-poc"]
assignees:
  - erdalgunes
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your inquiry! We're here to help.
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: textarea
    id: inquiry-description
    attributes:
      label: Question or Inquiry
      description: A clear and concise description of your question or inquiry
      placeholder: What would you like to know?
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does your inquiry fall under?
      options:
        - Setup/Installation
        - Development/Code
        - Documentation
        - Testing
        - Performance
        - General Usage
        - Other
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any additional context or information that might be relevant
      placeholder: Any background information that might help us understand your question better
    validations:
      required: false
  
  - type: textarea
    id: attempted-solutions
    attributes:
      label: What have you tried?
      description: Have you attempted any solutions or looked at existing documentation?
      placeholder: List any attempts or research you've done
    validations:
      required: false
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to make sure this question hasn't been asked before
          required: true
        - label: I have checked the documentation/wiki for relevant information
          required: true
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true